name: test coverage

on:
  - push

jobs:
  check:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustc, rust-std, cargo, llvm-tools, llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Run profiling tests
        run: |
          mkdir -p ./target/debug/coverage
          cargo test --no-fail-fast -p openmls
        env:
          CARGO_INCREMENTAL: '0'
          LLVM_PROFILE_FILE: 'target/debug/coverage/openmls-%p-%m.profraw'
          RUSTFLAGS: '-Cinstrument-coverage -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Cinstrument-coverage -Cpanic=abort -Zpanic_abort_tests -Z unstable-options --persist-doctests target/debug/'
          LIBCRUX_DISABLE_SIMD256: '1'

      - name: Run grcov
        id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ steps.coverage.outputs.report }}
          
